/**
 * test.c
 * John Brock
 * 19 Jun 2008
 * Purpose:  To test values generated by keyboard sequences
**/
#include<stdio.h>
#include<stdlib.h>
#include <iostream>
using namespace std;

int main(void){
 string input;
  
 fprintf(stderr, "Please input test data:");
 cin >> input;
 cout << input[0] << endl;
}
